options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-southeast1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi-app',
      '.'
    ]
    dir: 'backend-fastapi'

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-southeast1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi-app'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'fastapi-service',
      '--image', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi-app',
      '--region', 'global',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]

images:
  - 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/fastapi-repo/fastapi-app'
